const hi = "👋 Hi, I’m Guilherme"
const interested = "👀 I’m interested in being a professional Web Developer"
const learning = "🌱 Currently learning JavaScript"
const highschool = "📚 Finishing High School"
const lastproject = "🔗 Last project: https://live2you.com.br"
const contact = "📫 How to reach me: guimaggiorini@icloud.com"
